### ISSUE TITLE
Enable -Werror and /Wx flags in the pipeline

### ISSUE THREAD

**Issue by matheusgomes28** [matheusgomes28/base64pp#18]
Enable warnings as errors as the CMakePresets.json was recently introduced in #16 .

TODOS 📖 

1. Add `-Werror` to the `*-unix-*` presets in `CMakePresets.json` 🐧 
2. Add `/Wx` to the `vs*` presets in `CMakePresets.json` 🪟 
3. Make sure all compilation errors are fixed in the pipeline ⚒️
